print("*********** Profes ***********")
print("Rodriguez, Miguel ~ Soria, Lucia      -----> Introduccion a git")


print("\n*********** Alumnos ***********")

print("Rodriguez, Miguel                    -----> ACABO DE MODIFICAR")
print("Aballay, Camila Anahi                -----> ESCRIBIR AQUI")
print("Ali, Hector Oscar                    -----> ESCRIBIR AQUI")
print("Althaparro, Delfina                  -----> ESCRIBIR AQUI")
print("Alvarez, Lucia Evangelina            -----> ESCRIBIR AQUI")
print("Amarilla, Nerina Anabel              -----> ESCRIBIR AQUI")
print("Amaya Suarez, Thiago Rodrigo         -----> ESCRIBIR AQUI")
print("Aranda, Axel Juan Pablo              -----> ESCRIBIR AQUI")
print("Armellin, Ignacio                    -----> q ondaa")
print("Ataca, Mariana Estela                -----> ESCRIBIR AQUI")
print("Avila, Ramiro                        -----> ESCRIBIR AQUI")
print("Bardagi, Lucas Gonzalo               -----> ESCRIBIR AQUI")
print("Barraza, Marcos Luciano              -----> ESCRIBIR AQUI")
print("Barreto, Marcelo Javier              -----> ESCRIBIR AQUI")
print("Bejarano, Uriel                      -----> ESCRIBIR AQUI")
print("Bellver, Leandro Nicolás             -----> ESCRIBIR AQUI")
print("Benítez Paraná, Pedro Tomás Federico -----> ESCRIBIR AQUI")
print("Bernal, Tomas                        -----> ESCRIBIR AQUI")
print("Bogado, Edilberto Fabian             -----> ESCRIBIR AQUI")
print("Boscatto, Ezequiel Alejandro         -----> ESCRIBIR AQUI")
print("Cabrera, Camila Cruz                 -----> ESCRIBIR AQUI")
print("Cacholatti, Renzo Tobias             -----> ESCRIBIR AQUI")
print("Calabrese, Micaela Florencia         -----> ESCRIBIR AQUI")
print("Cancinos, Marisa Aylen               -----> ESCRIBIR AQUI")
print("Canelo, Luciano Nahuel               -----> ESCRIBIR AQUI")
print("Chandi, Matias Luciano               -----> ESCRIBIR AQUI")
print("Chaves, Yanina Belén                 -----> Buenas :)")
print("Chiumiento, Matias Emiliano          -----> ESCRIBIR AQUI")
print("Contreras Niglia, Lucas Alejandro    -----> ESCRIBIR AQUI")
print("Coronel Acosta, Gabriel Marcos       -----> Saludos")
print("Espinola, Yanina                     -----> ESCRIBIR AQUI")
print("Espinoza, Brenda Estefania           -----> ESCRIBIR AQUI")
print("Farias, Roberto Ivan                 -----> ESCRIBIR AQUI")
print("Ferreira, Flavia Agustina            -----> ESCRIBIR AQUI")
print("Figueroa Molina, Cesar David         -----> ESCRIBIR AQUI")
print("Fuentes, Lucero Daira                -----> ESCRIBIR AQUI")
print("Galeano, Mateo                       -----> ESCRIBIR AQUI")
print("Gallardo, Rocio Ayelen               -----> Buenas ")
print("Galvan, Andrea Agustina              -----> ESCRIBIR AQUI")
print("Gayo, Matias Federico                -----> ESCRIBIR AQUI")
print("Gil, Juan Ignacio                    -----> ESCRIBIR AQUI")
print("Grados Coronel, Angelica Melina      -----> ESCRIBIR AQUI")
print("Grela, Franco Maximiliano            -----> ESCRIBIR AQUI")
print("Ibañez, Joaquin Ivan                 -----> Aguante boca")
print("Ibarra, Franco Ezequiel              -----> ESCRIBIR AQUI")
print("Juarez, Santiago Nahuel              -----> ESCRIBIR AQUI")
print("Ledesma Miguele, Facundo Benjamin    -----> ESCRIBIR AQUI")
print("Lemoine, Joel Ezequiel               -----> ESCRIBIR AQUI")
print("Lizondi Fajardo, Piero Leandro       -----> ESCRIBIR AQUI")
print("Lopez, Nahuel Facundo                -----> ESCRIBIR AQUI")
print("Luque, Agustin Ivan Ramón            -----> ESCRIBIR AQUI")
print("Maquera Oyola, María Noelia          -----> ESCRIBIR AQUI")
print("Martinez, Leandro Agustín            -----> ESCRIBIR AQUI")
print("Nuñez, Alexis Nahuel                 -----> ESCRIBIR AQUI")
print("Olivera, Nicolás Jesús               -----> ESCRIBIR AQUI")
print("Padilla, Matias Nicolas              -----> ESCRIBIR AQUI")
print("Pereyra, Rocio Belen                 -----> ESCRIBIR AQUI")
print("Pierini, Ignacio                     -----> ESCRIBIR AQUI")
print("Poblete Insaurralde, Melina Soledad  -----> buenas noches:)")
print("Polcaro, Lucio                       -----> ESCRIBIR AQUI")
print("Quiroga, Pablo Nicolas               -----> ESCRIBIR AQUI")
print("Reinoso, Ryan Ruben                  -----> Ryan estuvo aquí")
print("Ribeiro, Julian Ezequiel             -----> ESCRIBIR AQUI")
print("Ríos, David                          -----> ESCRIBIR AQUI")
print("Rivas Ferreryra, Abiel Alberto       -----> Estoy haciendo mewing B)")
print("Sahonero, Cristina Denise            -----> ESCRIBIR AQUI")
print("Sanchez, Maria Macarena              -----> ESCRIBIR AQUI")
print("Sigales, Daiana Elizabeth            -----> ESCRIBIR AQUI")
print("Torres, Matias Oscar                 -----> ESCRIBIR AQUI")
print("Víctora, Tomas Alejandro             -----> ESCRIBIR AQUI")
print("Weschenfeller, Eliezer Micael        -----> ESCRIBIR AQUI")
print("Zarate, Katherine Daiana             -----> ESCRIBIR AQUI")
